apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: thundertech
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: ghcr.io/alphabraga/juris-site:d792a82039d961c3c4cad0171cf7e109b6d8fb09
        ports:
        - containerPort: 80