apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: thundertech
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: ghcr.io/alphabraga/juris-site:42601a491262460fc0a47f1219505826d5177dcf
        ports:
        - containerPort: 80
